[tool.poetry]
name = "python-machine-learning-book-3rd-edition"
version = "0.1.0"
description = ""
authors = ["David Lin"]
package-mode = false   # research repo; not published as a package
readme = "README.md"

[tool.poetry.dependencies]
python         = ">=3.10,<3.12"
numpy          = "^2.2.5"
scipy          = "^1.15.2"
scikit-learn   = "^1.2"          # added; separate from torch
torch          = "^2.7.0"
tensorflow     = "^2.13.0"       # added
xgboost        = "^3.0.0"
shap           = "^0.47.2"
optuna         = "^4.3.0"
statsmodels    = "^0.14.4"
plotly         = "^6.0.1"
seaborn        = "^0.13.2"
matplotlib     = "^3.10.1"
kagglehub      = "^0.3.11"
watermark      = "^2.5.0"
ipykernel      = "^6.29.5"
mlxtend = "^0.23.4"

[tool.poetry.group.dev.dependencies]
jupyter        = "^1.1.1"

[build-system]
requires       = ["poetry-core"]
build-backend  = "poetry.core.masonry.api"
